name: Build DXDLL

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Download Dependencies (d3d8.lib, d3dx8.lib, headers)
      shell: cmd
      run: |
        curl -L -o dxdll-source/d3d8.lib https://github.com/apitrace/dxsdk/raw/master/Lib/x86/d3d8.lib
        curl -L -o dxdll-source/d3dx8.lib https://github.com/apitrace/dxsdk/raw/master/Lib/x86/d3dx8.lib
        curl -L -o dxdll-source/d3d8types.h https://github.com/apitrace/dxsdk/raw/master/Include/d3d8types.h
        curl -L -o dxdll-source/d3d8caps.h https://github.com/apitrace/dxsdk/raw/master/Include/d3d8caps.h
        
    - name: Build
      working-directory: dxdll-source
      shell: cmd
      run: msbuild DX8Hook.vcxproj /p:Configuration=Release /p:Platform=Win32 /p:LibraryPath=".;$(LibraryPath)" /p:IncludePath=".;$(IncludePath)" -verbosity:normal

    - name: List Release Directory
      if: always()
      run: dir dxdll-source\Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dxdll-release
        path: dxdll-source/Release/d3d8.dll
